# Site settings
title: PCF Dev
email: appdev@kids.wustl.edu
description: > # this means to ignore newlines until "baseurl:"
  PCFDev is the site published by the Pediatric Computing Facilities Development
  team at Washington University in St. Louis.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wus.tl/pcf" # the base hostname & protocol for your site
twitter_username: wustl
github_username:  pcfdev

# Build settings
markdown: kramdown
